### ISSUE TITLE
什么时候能完成啊,很期待啊

### ISSUE THREAD

**Issue by Matrix42** [wrfly/php-offline-download#1]

**Comment by wrfly** [comment]
啊，这个流产了... 工作了，懒得写这个了。

给你提供下思路：

1. 前端PHP画个页面，往数据库里写下载链接，文件名等元信息
2. 后端有个用shell写的下载任务（下载工具： axel多进程下载器），每分钟读数据库一次，抓取下载链接，下载到本地（可以有多台服务器），注意对下载任务的更新（下载进度，开始时间，结束时间，超时）
3. 下载完成后生成一个下载链接（依据配置的域名和文件名，可以创建一个MD5
的二级文件夹保存下载文件），并更新数据库
4. 下载完成后，可以通过邮件通知下载者（不能是匿名下载，要记录下载者的邮箱）
5. 每个下载节点上用Nginx作为网络服务器，通过下载链接下载文件
